#!/usr/bin/env python
# coding: utf-8
import sys
import csv
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--delimiter', help='Input data delimiter', required=True)
    args = parser.parse_args()
    delimiter = args.delimiter.decode('string_escape')

    input_data = sys.stdin
    if delimiter == '\n':
        input_data = [col.replace('\n', ',') for col in input_data.read().strip().split('\n%\n')]
        print input_data
        delimiter = ','
    data = csv.reader(input_data, delimiter=delimiter)

    writer = csv.writer(sys.stdout, delimiter=',')
    writer.writerows(data)
